[package]
name = "service"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = []

[dependencies]
async-trait = "0.1.57"
rpc = { path = "../rpc" }
serde = { version = "1.0.144", features = ["derive"] }
